# -*- coding: utf-8 -*-
"""Assignment_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1id3lri88iRQX_fvfWgaD_xHdCPJnz-By
"""

with open("data.txt","w") as file:
  file.write("Emp_ID,Name,Department,Salary\n")
  file.write("101-Alice-HR-60000\n")
  file.write("102-Bob-Engineering-85000\n")
  file.write("103-Charlie-Marketing-70000\n")
  file.write("104-David-Engineering-92000\n")
  file.write("105-Eva-HR-65000\n")
  print("File database created;")

print('Enter your choice : ')
print('1. Create ;')
print('2. Update ;')
print('3. Read ;')
print('4. Delete ;')
ip = int(input())

if (ip == 1):
  id = input("Enter id :")
  name = input("Enter Name :")
  department = input("Enter Department :")
  salary = input("Enter salary :")
  str1 = id +"-"+ name +"-"+ department +"-"+ salary + "\n"
  file = open("data.txt","w")
  data = file.write(str1)
  file.close()
  print('Data added successfully;')

elif(ip == 2):
  up_id = input("Enter emp_id to update : ")
  up_data = input("Enter the data to update : ")+"\n"

  with open("data.txt", "r") as file:
    lines = file.readlines()

  update_lines = []
  for line in lines:
    if up_id in line:
      update_lines.append(up_data)
    else :
      update_lines.append(line)

  with open("data.txt", "w") as file:
    file.writelines(update_lines)

  print('Data updated successfully;')

elif(ip == 3):
  file = open("data.txt", "r")
  data = file.read()
  print(data)
  file.close()
  print('-x-\n')

elif(ip == 4):

  del_id = input("Enter emp_id to delete : ")
  with open("data.txt", "r") as file:
    lines = file.readlines()

  delete_lines = []
  for line in lines:
    if del_id not in line:
      delete_lines.append(line)

  with open("data.txt", "w") as file:
    file.writelines(delete_lines)

  print('Deleted Sucessfully')

else :
  print("Invalid Operation!!!")
