# -*- coding: utf-8 -*-
"""Assignment5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P9pdO6vkrwjv6aMskQVd8Gh0HPWjEJWA
"""

def adding(fun):
  def waiting(*args,**kwargs):
    print("Processing...")
    i = 0
    result = fun(*args,**kwargs)
    while i< 5:
      print("-")
      i+= 1

    return result

  return waiting

@adding
def add(a,b):
  return a+b

print("Result : ",add('alpha','beta'))