# -*- coding: utf-8 -*-
"""Assignment_3(pandas).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zDO2cHGNIAd5Ie2yYD1aAv8UM87i8YSG
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install pandas

import pandas as pd

columns = ['emp_id' , 'name','department', 'salary']

df = pd.DataFrame(columns= columns)

df.to_csv('database.csv',index = False)

print('Enter your choice : ')
print('1. Create ;')
print('2. Update ;')
print('3. Read ;')
print('4. Delete ;')
ip = int(input())

if (ip == 1):
  id = input("Enter id :")
  name = input("Enter Name :")
  department = input("Enter Department :")
  salary = input("Enter salary :")
  init_data = pd.DataFrame([{'id':id,'name':name,'department':department,'salary':salary}])
  df = pd.concat([df, init_data], ignore_index=True)
  df.to_csv('database.csv', index=False)
  print('Data added successfully;')

elif(ip == 2):
    df = pd.read_csv('database.csv')
    up_id = input("Enter emp_id to update : ")

    if up_id in df['id'].astype(str).values:
        new_name = input("Enter new Name : ")
        new_department = input("Enter new Department : ")
        new_salary = input("Enter new salary : ")

        df.loc[
            df['id'].astype(str) == up_id, ['name', 'department', 'salary']] = [new_name, new_department, new_salary]

        df.to_csv('database.csv', index=False)
        print('Updated Successfully')
    else:
        print('ID not found!')




elif(ip == 3):
  df = pd.read_csv('database.csv')
  print('-x-\n')

elif(ip == 4):
  del_id = input("Enter emp_id to delete : ")
  df = df[df['id' != del_id]]
  df.to_csv('database.csv', index=False)
  print('Deleted Sucessfully')

else :
  print("Invalid Operation!!!")



